version: '3'
services:
  db:
    image: "postgres:12"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - backend
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    depends_on:
      - "db"
    ports:
      - 8080:8080

  api:
    build: ./api
    networks:
      - backend
    depends_on:
      - "db"
    ports:
      - "3001:3001"

  front:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - "api"
    stdin_open: true
    tty: true

volumes:
  my_dbdata:

networks:
  backend:
    driver: bridge
