version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "my_postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5439:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  my_dbdata: ./my_dbdata